# Site settings
title: Rubén Martínez Vilar
email: rub3nmv@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Rubén Martínez Vilar Portfolio. Multimedia engineer. Earthling.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "rubenmv.github.io" # the base hostname & protocol for your site
twitter_username: rub3nvm
github_username:  rubenmv

# Styles
sass:
  style: compressed

# Build settings
highlighter: rouge
markdown: kramdown
author:
  name: 'Rub&eacute;n Mart&iacute;nez Vilar'
  url: https://twitter.com/rub3nmv
# Blog
# Creates the posts into blog folder
permalink: '/blog/:year/:title/'
gems: [jekyll-paginate]
paginate: 10
# This allows to call paginator from subfolder blog/index.html and separates pages in folders
paginate_path: "/blog/page:num/"
